name: CI

on:
    pull_request:
        branches: [ main ]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master

  inputhandlertest:
    name: Input handler tests
    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      APACHE_DIR: "/etc/apache2"
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
        ports:
         - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Setup PHP and the extensions also the tools
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer:v2
        extensions: cli fpm mysql json opcache mbstring xml gd curl intl

    - name: Start mqsql daemon.
      run: |
          sudo systemctl start mysql

    - name: Verify mysql.
      run: |
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -u root -p${{ env.MYSQL_ROOT_PASSWORD }} --execute "SHOW DATABASES"

    - name: Install CV command
      run: |
          curl -LsS https://download.civicrm.org/cv/cv.phar -o cv
          sudo mv cv /usr/local/bin/
          sudo chmod +x /usr/local/bin/cv

    - name: Basic apache module and config
      run: |
          sudo apt-get install libapache2-mod-php7.4
          sudo a2enmod rewrite
          sudo mv apache2.conf ${{ env.APACHE_DIR }}/apache2.conf

    - name: Run tests.
      env:
        PROJECT_BASE_PATH: ".."
        SITE_NAME: "composer-site.com"
        DB_NAME: ${{ env.MYSQL_DATABASE }}
        DB_HOST: "127.0.0.1"
        DB_PORT: ${{ job.services.mysql.ports['3306'] }}
        DB_USER: "root@localhost"
        MYSQL_DB_PASS: ${{ env.MYSQL_ROOT_PASSWORD }}
        SITE_ADMIN_NAME: "admin"
        SITE_ADMIN_PW: "jPoLvGGGV5"
        APACHE_CONF_DIR: ${{ env.APACHE_DIR }}
        LOCAL_DEPLOY_TARGET: "/var/www/html"
        COMPOSER_APP: composer
      run: |
          ./tests/test_CIBuild.sh
          ./tests/test_DrupalBuild.sh
          ./tests/test_DrupalCivicrmBuild.sh
